### ISSUE TITLE
when done the jobs and open 3dsmax,it only show "LEGO Importer loaded" in maxscript 

### ISSUE THREAD

**Issue by JOJOyh** [stargatefreak92/LEGO-3ds-Max-importer#5]
when i download the project,first i run .NET project and got "LDraw.dll",then i copied it to folder 'scritps\LEGO_Importer',then i open max,there was nothing but only show "LEGO Importer loaded" in maxscript listener.
is there any step went wrong?

**Comment by NickEastNL** [comment]
Sincere apologies for the extremely late reply. Unfortunately, due to me having moved on from 3ds Max, I no longer support this. As it was created for, if I remember correctly, 3ds max 2019, I assume it no longer works for later versions, since every second version of Max requires such plugins to be rebuilt. I currently intend to move the library over to Houdini when time permits.
